version: "3"

services:
  server_1:
    build: './'
    command: nodemon src/backend/index.js
    ports:
      - '8000:8000'
    environment:
      DEV_DB_HOST: pg_1_db
      DEV_DB_PORT: 5432
      DEV_DB_USER: root
      DEV_DB_PSWD: root
      DEV_DB_NAME: boiler_room
      NODE_ENV: development
    volumes:
      - ./public/:/usr/app/public/
      - ./src/:/usr/app/src/
      - ./package.json:/usr/app/package.json
      - ./console.js:/usr/app/console.js
      - ./webpack.config.js:/usr/app/webpack.config.js
    container_name: server_1_container

  pg_1_db:
    image: postgres:9.6-alpine
    ports:
      - '5431:5432'
    environment:
      # these are PG builtin env vars
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: boiler_room

    container_name: pg_1_db_container